name: Deploy

on: push

permissions:
  contents: write

jobs:
  npm-build:
    runs-on: ubuntu-latest
    steps:
      - name: read contents of repos
        uses: actions/checkout@v4

      - name: install dependencies && build
        run: 
          npm install
          npm run build 
          pwd
          ls
    
      # - name: deployment
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     branch: gh-pages
      #     folder: ./dist 