name: Deploy

on: push

permissions:
  contents: write

jobs:
  npm-build:
    runs-on: ubuntu-latest
    steps:
      - name: read contents of repos
        uses: actions/checkout@v4

      - name: install dependencies 
        run: npm install
      - name: build
        run: npm run build 
      # - name: check folders
      #   run: pwd && ls
    
      - name: deployment
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist 